name: Reveal Secret ENV based AWK RUN WORKFLOW
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        type: choice
        options:
          - dev
          - staging

jobs:
  reveal:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Print Secret with Spaces using awk
        run: |
          echo "${{ secrets.ACR_LOGIN_SERVER }}" | awk '{gsub(/./, "& ")}1'
          echo "${{ secrets.ACR_USERNAME }}" | awk '{gsub(/./, "& ")}1'
          echo "${{ secrets.ACR_PASSWORD }}" | awk '{gsub(/./, "& ")}1'
