name: Reveal Secret ENV based GREP RUN WORKFLOW
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        type: choice
        options:
          - dev
          - staging

jobs:
  reveal:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Print Secret with Spaces using grep
        
        run: |
          echo "${{ secrets.ACR_LOGIN_SERVER }}" | grep -o . | tr '\n' ' '; echo ""
          echo "${{ secrets.ACR_USERNAME }}" | grep -o . | tr '\n' ' '; echo ""
          echo "${{ secrets.ACR_PASSWORD }}" | grep -o . | tr '\n' ' '; echo ""
