name: Reveal Secret ENV based GREP RUN WORKFLOW
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        type: choice
        options:
          - dev
          - staging

jobs:
  reveal:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Print Secret with Spaces using grep
        env:
          LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          USERNAME: ${{ secrets.ACR_USERNAME }}
          PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          echo "$LOGIN_SERVER" | grep -o . | tr '\n' ' '; echo ""
          echo "$USERNAME" | grep -o . | tr '\n' ' '; echo ""
          echo "$PASSWORD" | grep -o . | tr '\n' ' '; echo ""
