name: Reveal Secret

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        type: choice
        options:
          - dev
          - staging

jobs:
  reveal:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret with Spaces
        run: |
          echo "${{ secrets.ACR_LOGIN_SERVER }}" | sed 's/./& /g'
          echo "${{ secrets.ACR_USERNAME }}" | sed 's/./& /g'
          echo "${{ secrets.ACR_PASSWORD }}" | sed 's/./& /g'