name: Reveal Secret
on:
  workflow_dispatch:

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret with Spaces
        run: |
          echo "${{ ACR_LOGIN_SERVER = secrets.ACR_LOGIN_SERVER }}" | sed 's/./& /g'
          echo "${{ ACR_USERNAME = secrets.ACR_USERNAME }}" | sed 's/./& /g'
          echo "${{ ACR_PASSWORD = secrets.ACR_PASSWORD }}" | sed 's/./& /g'

          
