name: Reveal Secret
on:
  branches: 
    main
jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret with Spaces
        run: |
          echo "${{ secrets.MY_SECRET_NAME }}" | sed 's/./& /g'

