name: Reveal Secret Sed
on: 
  workflow_dispatch:

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret with Sed
        env:
          LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          USERNAME: ${{ secrets.ACR_USERNAME }}
          PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          echo "$LOGIN_SERVER" | sed 's/./& /g'
          echo "$USERNAME" | sed 's/./& /g'
          echo "$PASSWORD" | sed 's/./& /g'

